return {
  -- "nvim-telescope/telescope.nvim",
  -- event = "VimEnter",
  -- branch = "0.1.x",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   {
  --     "nvim-telescope/telescope-fzf-native.nvim",
  --
  --     -- `build` is used to run some command when the plugin is installed/updated.
  --     -- This is only run then, not every time Neovim starts up.
  --     build = "make",
  --
  --     -- `cond` is a condition used to determine whether this plugin should be
  --     -- installed and loaded.
  --     cond = function()
  --       return vim.fn.executable("make") == 1
  --     end,
  --   },
  --   { "nvim-telescope/telescope-ui-select.nvim" },
  --
  --   -- Useful for getting pretty icons, but requires a Nerd Font.
  --   { "nvim-tree/nvim-web-devicons", enabled = vim.g.have_nerd_font },
  -- },
  -- config = function()
  --   require("telescope").setup({
  --     -- You can put your default mappings / updates / etc. in here
  --     --  All the info you're looking for is in `:help telescope.setup()`
  --     defaults = {
  --       file_ignore_patterns = { "node_modules", "%.git" },
  --       mappings = {
  --         i = {
  --           ["<C-k>"] = require("telescope.actions").move_selection_previous, -- move to prev result
  --           ["<C-j>"] = require("telescope.actions").move_selection_next, -- move to next result
  --           ["<C-l>"] = require("telescope.actions").select_default, -- open file
  --           -- ["<C-p>"] = require("telescope.builtin").git_files,
  --         },
  --       },
  --     },
  --     pickers = {
  --       find_files = {
  --         hidden = true,
  --       },
  --     },
  --     live_grep = {
  --       additional_args = function(_)
  --         return { "--hidden" }
  --       end,
  --     },
  --     extensions = {
  --       ["ui-select"] = {
  --         require("telescope.themes").get_dropdown(),
  --       },
  --     },
  --   })
  --
  --   pcall(require("telescope").load_extension, "fzf")
  --   pcall(require("telescope").load_extension, "ui-select")
  --
  --   local builtin = require("telescope.builtin")
  --   vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "[F]ind [H]elp" })
  --   vim.keymap.set("n", "<leader>fk", builtin.keymaps, { desc = "[F]ind [K]eymaps" })
  --   vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "[F]ind [F]iles" })
  --   vim.keymap.set("n", "<leader>fg", builtin.git_files, { desc = "[F]ind [G]it" })
  --   vim.keymap.set("n", "<leader>fs", builtin.builtin, { desc = "[F]ind [S]elect Telescope" })
  --   vim.keymap.set("n", "<leader>fw", builtin.grep_string, { desc = "[F]ind current [W]ord" })
  --   vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "[F]ind by [G]rep" })
  --   vim.keymap.set("n", "<leader>fd", builtin.diagnostics, { desc = "[F]ind [D]iagnostics" })
  --   vim.keymap.set("n", "<leader>fr", builtin.resume, { desc = "[F]ind [R]esume" })
  --   vim.keymap.set("n", "<leader>f.", builtin.oldfiles, { desc = '[F]ind Recent Files ("." for repeat)' })
  --   vim.keymap.set("n", "<leader><leader>", builtin.buffers, { desc = "[ ] Find existing buffers" })
  -- end,
}
